final product = [
  {
    'title': 'Men\'s Nike Shoes',
    'price': 5999,
    'sizes': [6, 7, 8, 9, 10],
    'id': '1',
    'company': 'Nike',
    'imageUrl': 'assets/images/shoe1.jpg',
  },
  {
    'title': 'Men\'s Nike Shoes',
    'price': 7999,
    'sizes': [6, 7, 8, 9, 10],
    'id': '2',
    'company': 'Nike',
    'imageUrl': 'assets/images/shoe2.jpg',
  },
  {
    'title': 'Men\'s Nike Shoes',
    'price': 10999,
    'sizes': [6, 7, 8, 9, 10],
    'id': '3',
    'company': 'Nike',
    'imageUrl': 'assets/images/shoe3.jpg',
  },
  {
    'title': 'Men\'s Nike Shoes',
    'price': 14899,
    'sizes': [6, 7, 8, 9, 10],
    'id': '4',
    'company': 'Nike',
    'imageUrl': 'assets/images/shoe4.jpg',
  },
  {
    'title': 'Men\'s Nike Shoes',
    'price': 3999,
    'sizes': [6, 7, 8, 9, 10],
    'id': '5',
    'company': 'Nike',
    'imageUrl': 'assets/images/shoe5.jpg',
  },
  {
    'title': 'Men\'s Adidas Shoes',
    'price': 4999,
    'sizes': [6, 7, 8, 9, 10],
    'id': '6',
    'company': 'Adidas',
    'imageUrl': 'assets/images/shoe6.jpeg',
  },
  {
    'title': 'Men\'s Adidas Shoes',
    'price': 2999,
    'sizes': [6, 7, 8, 9, 10],
    'id': '7',
    'company': 'Adidas',
    'imageUrl': 'assets/images/shoe7.jpg',
  },
  {
    'title': 'Men\'s Bata Shoes',
    'price': 1299,
    'sizes': [6, 7, 8, 9, 10],
    'id': '8',
    'company': 'Bata',
    'imageUrl': 'assets/images/shoe8.webp',
  },
  {
    'title': 'Men\'s Bata Shoes',
    'price': 890,
    'sizes': [6, 7, 8, 9, 10],
    'id': '9',
    'company': 'Bata',
    'imageUrl': 'assets/images/shoe9.jpeg',
  },
  {
    'title': 'Men\'s Puma Shoes',
    'price': 5399,
    'sizes': [6, 7, 8, 9, 10],
    'id': '10',
    'company': 'Puma',
    'imageUrl': 'assets/images/shoe10.jpg',
  },
  {
    'title': 'Men\'s Puma Shoes',
    'price': 3998,
    'sizes': [6, 7, 8, 9, 10],
    'id': '11',
    'company': 'Puma',
    'imageUrl': 'assets/images/shoe11.jpg',
  },
  {
    'title': 'Men\'s Puma Shoes',
    'price': 4999,
    'sizes': [6, 7, 8, 9, 10],
    'id': '12',
    'company': 'Puma',
    'imageUrl': 'assets/images/shoe12.jpg',
  },
  {
    'title': 'Men\'s Adidas Shoes',
    'price': 2899,
    'sizes': [6, 7, 8, 9, 10],
    'id': '13',
    'company': 'Adidas',
    'imageUrl': 'assets/images/shoe13.jpg',
  },
  {
    'title': 'Men\'s Adidas Shoes',
    'price': 3990,
    'sizes': [6, 7, 8, 9, 10],
    'id': '14',
    'company': 'Adidas',
    'imageUrl': 'assets/images/shoe14.jpg',
  },
  {
    'title': 'Men\'s Adidas Shoes',
    'price': 2799,
    'sizes': [6, 7, 8, 9, 10],
    'id': '15',
    'company': 'Adidas',
    'imageUrl': 'assets/images/shoe15.jpg',
  },
  {
    'title': 'Men\'s Adidas Shoes',
    'price': 6999,
    'sizes': [6, 7, 8, 9, 10],
    'id': '16',
    'company': 'Adidas',
    'imageUrl': 'assets/images/shoe16.jpg',
  },
  {
    'title': 'Men\'s Puma Shoes',
    'price': 2999,
    'sizes': [6, 7, 8, 9, 10],
    'id': '17',
    'company': 'Puma',
    'imageUrl': 'assets/images/shoe17.jpg',
  },
];
final cart = [
  {
    'title': 'Men\'s jordan Shoes',
    'price': 5999,
    'sizes': [6, 7, 8, 9, 10],
    'id': '18',
    'company': 'Jordan Poole',
    'imageUrl': 'assets/images/shoe17.png',
  },
];
